org: yeukfei02
app: hacker-news-node-ts-serverless
service: hacker-news-node-ts-serverless

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks
